name: "llama2-7B-hf-tp-4"
platform: "ensemble"
max_batch_size: 4096
input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "max_output_len"
    data_type: TYPE_INT32
    dims: [ 1 ]
  },
  {
    name: "top_k"
    data_type: TYPE_INT32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "top_p"
    data_type: TYPE_FP32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "temperature"
    data_type: TYPE_FP32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "len_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "repetition_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "random_seed"
    data_type: TYPE_UINT64
    dims: [ 1 ]
    optional: true
  },
  {
    name: "beam_width"
    data_type: TYPE_INT32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "start_id"
    data_type: TYPE_INT32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "end_id"
    data_type: TYPE_INT32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "stop_words_list"
    data_type: TYPE_INT32
    dims: [ 2, -1 ]
    optional: true
  },
  {
    name: "bad_words_list"
    data_type: TYPE_INT32
    dims: [ 2, -1 ]
    optional: true
  }
]
output [
  {
    name: "output"
    data_type: TYPE_STRING
    dims: [ -1, -1 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "llama2-7B-hf-tp-4_tokenizer"
      model_version: -1
      input_map {
        key: "query"
        value: "text"
      }
      input_map {
        key: "max_output_len"
        value: "max_output_len"
      }
      output_map {
        key: "input_ids"
        value: "input_ids"
      }
      output_map {
        key: "sequence_lengths"
        value: "sequence_lengths"
      }
    },
    {
      model_name: "llama2-7B-hf-tp-4_llama_decoder"
      model_version: -1
      input_map {
        key: "input_ids"
        value: "input_ids"
      }
      input_map {
        key: "request_output_len"
        value: "max_output_len"
      }
      input_map {
        key: "input_lengths"
        value: "sequence_lengths"
      }
      input_map {
        key: "runtime_top_k"
        value: "top_k"
      }
      input_map {
        key: "runtime_top_p"
        value: "top_p"
      }
      input_map {
        key: "temperature"
        value: "temperature"
      }
      input_map {
        key: "len_penalty"
        value: "len_penalty"
      }
      input_map {
        key: "repetition_penalty"
        value: "repetition_penalty"
      }
      input_map {
        key: "random_seed"
        value: "random_seed"
      }
      input_map {
        key: "beam_width"
        value: "beam_width"
      }
      input_map {
        key: "start_id"
        value: "start_id"
      }
      input_map {
        key: "end_id"
        value: "end_id"
      }
      input_map {
        key: "stop_words_list"
        value: "stop_words_list"
      }
      input_map {
        key: "bad_words_list"
        value: "bad_words_list"
      }
      output_map {
        key: "output_ids"
        value: "output_ids"
      }
    },
    {
      model_name: "llama2-7B-hf-tp-4_detokenizer"
      model_version: -1
      input_map {
        key: "tokens_batch"
        value: "output_ids"
      }
      input_map {
        key: "input_sequence_lengths"
        value: "sequence_lengths"
      }
      output_map {
        key: "output"
        value: "output"
      }
    }
  ]
}
